version: '3'
services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    hostname: kafka
    image: wurstmeister/kafka
    ports:
      - "19092:9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERFISED_PORT: 19092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ws-text:3:1:compact,wet-rtc:2:1"
      KAFKA_BROKER_ID: "1"
      SASL_USERNAME: G32SDBBRFPEAASUY
      SASL_PASSWORD: CWKKMU/c6lqUnuEYscRwk2jBIEhVRsdOBm7ymA3c2KhqJp02l+QBhoV/LBeLYcU9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    external:
      name: fan